---
name: build-pluto
on:
    push:
        branches:
            - main
        paths-ignore:
            - '**/README.md'
            - 'juno'
    schedule:
     - cron: '05 10 * * *'  # 10:05am UTC everyday
    workflow_dispatch:

env:
  IMAGE_NAME: "pluto"
  IMAGE_DESC: "Experiements with fedora ostree containers"

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Image Metadata
          uses: docker/metadata-action@v5
          id: meta
          with:
            images: |
              ${{ env.IMAGE_NAME }}
    
            labels: |
              io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
              org.opencontainers.image.description=${{ env.IMAGE_DESC }}
              org.opencontainers.image.title=${{ env.IMAGE_NAME }}

        - name: Build image
          id: build_image
          uses: redhat-actions/buildah-build@v2
          with:
            containerfiles: |
                ./${{ env.IMAGE_NAME }}
            image: ${{ env.IMAGE_NAME }}
            labels: ${{ steps.meta.outputs.labels }}
            oci: false

        - name: Push Image to GHCR
          uses: redhat-actions/push-to-registry@v2
          id: push
          with:
            image: ${{ steps.build_image.outputs.image }}
            registry: "ghcr.io/${{ github.repository_owner }}"
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            extra-args: |
              --disable-content-trust
