---
name: build-juno
on:
    push:
        branches:
            - main
        paths-ignore:
            - '**/README.md'
            - 'pluto/*'
    schedule:
     - cron: '05 10 * * *'  # 10:05am UTC everyday
    workflow_dispatch:

jobs:
  build_push:
    name: Build and push image
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image_name: "juno"
      base_image_name: "silverblue"
